package ua.tqs;

// Generated by Selenium IDE
import org.junit.jupiter.api.*;

import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class RedmineTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @BeforeEach
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void redmineTest() {
        // Test name: RedmineTest
        // Step # | name | target | value
        // 1 | open | / |
        driver.get("http://demo.redmine.org/");
        // 2 | setWindowSize | 1360x684 |
        driver.manage().window().setSize(new Dimension(1360, 684));
        // 3 | click | linkText=Sign in |
        driver.findElement(By.linkText("Sign in")).click();
        // 4 | click | id=username |
        driver.findElement(By.id("username")).click();
        // 5 | type | id=username | tiagomendes
        driver.findElement(By.id("username")).sendKeys("tiagomendes");
        // 6 | click | id=password |
        driver.findElement(By.id("password")).click();
        // 7 | type | id=password | 12345
        driver.findElement(By.id("password")).sendKeys("12345");
        // 8 | click | name=login |
        driver.findElement(By.name("login")).click();
        // 9 | click | linkText=tiagomendes |
        driver.findElement(By.linkText("tiagomendes")).click();
        // 10 | click | id=top-menu |
        driver.findElement(By.id("top-menu")).click();
        // 11 | click | linkText=Sign out |
        driver.findElement(By.linkText("Sign out")).click();
        // 12 | click | linkText=Sign in |
        driver.findElement(By.linkText("Sign in")).click();
    }
}
